version: "3.8"
services:
  server:
    build: ./server
    ports:
      - 8080:8080
      - 1935:1935
      - 1985:1985
  publisher:
    depends_on: [server]
    build: ./publisher
  consumer:
    depends_on: [publisher]
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
    devices:
      - "/dev/snd:/dev/snd"
    build: ./client
